import type { APIEvent } from "@solidjs/start/server";
import satori from 'satori'
import { visit } from 'unist-util-visit'
import cfg from "~/constant";

export async function GET(event: APIEvent) {
  try {
    const { searchParams } = new URL(event.request.url);

    const hasTitle = searchParams.has('title');
    const hasDesc = searchParams.has('desc');
    const title = hasTitle
      ? searchParams.get('title')?.slice(0, 100)
      : '';
    const desc = hasDesc
      ? searchParams.get('desc')?.slice(0, 100)
      : 'no desc?';

    return new Response(`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" data-stacking-context="true" aria-owns="lenis1" width="683" height="319" viewBox="175 163 683 319">
    <!-- Generated by dom-to-svg from http://localhost:3000/milieuim-logos -->
    <style/>
    <g data-stacking-layer="rootBackgroundAndBorders"/>
    <g data-stacking-layer="childStackingContextsWithNegativeStackLevels"/>
    <g data-stacking-layer="inFlowNonInlineNonPositionedDescendants"/>
    <g data-stacking-layer="nonPositionedFloats"/>
    <g data-stacking-layer="inFlowInlineLevelNonPositionedDescendants"/>
    <g data-stacking-layer="childStackingContextsWithStackLevelZeroAndPositionedDescendantsWithStackLevelZero"/>
    <g data-stacking-layer="childStackingContextsWithPositiveStackLevels"/>
    <g data-tag="html" id="lenis1" class="lenis" data-z-index="auto" data-stacking-context="true" aria-owns="head1 body1 auto-scroll1 grammarly-desktop-integration1">
        <g data-tag="head" id="head1" data-z-index="auto" data-stacking-context="true" aria-owns="meta1 meta2 link1 script1 script2 plugin-0 vite-client style1 style2 style3 style4 style5 link2 meta3 meta4 meta5 meta6 meta7 title1 link3 meta8 meta9 meta10 meta11 meta12 meta13">
            <g data-tag="meta" id="meta1" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="meta" id="meta2" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="link" id="link1" data-z-index="auto" data-stacking-context="true" role="link"/>
            <g data-tag="script" id="script1" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="script" id="script2" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="script" id="plugin-0" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="script" id="vite-client" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="style" id="style1" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="style" id="style2" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="style" id="style3" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="style" id="style4" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="style" id="style5" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="link" id="link2" data-z-index="auto" data-stacking-context="true" role="link"/>
            <g data-tag="meta" id="meta3" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="meta" id="meta4" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="meta" id="meta5" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="meta" id="meta6" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="meta" id="meta7" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="title" id="title1" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="link" id="link3" data-z-index="auto" data-stacking-context="true" role="link"/>
            <g data-tag="meta" id="meta8" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="meta" id="meta9" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="meta" id="meta10" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="meta" id="meta11" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="meta" id="meta12" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="meta" id="meta13" data-z-index="auto" data-stacking-context="true"/>
        </g>
        <g data-tag="body" id="body1" data-z-index="auto" data-stacking-context="true" role="document" aria-owns="app script3 script4 script5">
            <g data-tag="div" id="app" data-z-index="auto" data-stacking-context="true" aria-owns="main1">
                <g data-tag="main" id="main1" data-z-index="auto" data-stacking-context="true" role="main" aria-owns="flex1 !fixed1">
                    <g data-tag="div" id="flex1" class="flex flex-col bg-zinc-50 dark:bg-[#171717] min-h-screen items-center" data-z-index="auto" data-stacking-context="true" aria-owns="top-01 flex3 relative2">
                        <g data-stacking-layer="rootBackgroundAndBorders">
                            <rect width="1032" height="1611.2890625" x="0" y="-810" fill="rgb(250, 250, 250)"/>
                        </g>
                        <g data-tag="header" id="top-01" class=" top-0 w-full flex items-center justify-between mx-3 xl:mx-5 2xl:mx-6 pointer-events-none" data-z-index="auto" data-stacking-context="true" aria-owns="flex2 pointer-events-auto1">
                            <a href="http://localhost:3000/" data-tag="a" id="flex2" class="flex items-center justify-center text-lg 2xl:text-2xl font-semibold rounded-sm text-sprout-650 overflow-visible group pointer-events-auto ml-3 active" data-z-index="auto" data-stacking-context="true" role="link" aria-owns="relative1">
                                <g data-tag="div" id="relative1" class="relative h-4" data-z-index="auto" data-stacking-context="true" aria-owns="absolute1 absolute2">
                                    <g data-tag="div" id="absolute1" class="absolute h-4 w-4 dark:bg-sprout-400 rounded-full transition-all duration-500 delay-300 transform-gpu shadow-md bg-sprout-200 top-0 left-0" data-z-index="auto" data-stacking-context="true"/>
                                    <g data-tag="div" id="absolute2" class="absolute leading-none text-ouchi-200 text-shadow-xl dark:text-slate-200 text-nowrap font-sans" data-z-index="auto" data-stacking-context="true" aria-owns="i-ci:leaf1">
                                        <g data-tag="div" id="i-ci:leaf1" class="i-ci:leaf w-6 h-6 text-sprout-600" data-z-index="auto" data-stacking-context="true"/>
                                    </g>
                                </g>
                            </a>
                            <g data-tag="div" id="pointer-events-auto1" class="pointer-events-auto backdrop-blur-sm rounded-bl-2xl" data-z-index="auto" data-stacking-context="true" aria-owns="bg-background1">
                                <g data-tag="nav" id="bg-background1" class="bg-background flex items-center justify-end relative px-2 py-1.5" data-z-index="auto" data-stacking-context="true" role="navigation" aria-owns="bg-transparent1 bg-transparent2 bg-transparent3 bg-transparent4">
                                    <g data-stacking-layer="childStackingContextsWithPositiveStackLevels">
                                        <g data-tag="button" id="bg-transparent1" class="bg-transparent font-sans px-1.5 py-1 z-10 text-neutral-500 hover:text-neutral-600 rounded-md transition ease-in delay-200 [&amp;:not(:hover)]:opacity-0" data-z-index="10" data-stacking-context="true" opacity="0" role="button" aria-labelledby=""/>
                                        <g data-tag="button" id="bg-transparent2" class="bg-transparent font-sans px-1.5 py-1 z-10 text-neutral-500 hover:text-neutral-600 rounded-md transition ease-in delay-200" data-z-index="10" data-stacking-context="true" role="button" aria-labelledby="">
                                            <text color="rgb(115, 115, 115)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(115, 115, 115)" text-anchor="start" text-rendering="auto" unicode-bidi="normal" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(115, 115, 115)"/>
                                        </g>
                                        <g data-tag="button" id="bg-transparent3" class="bg-transparent font-sans px-1.5 py-1 z-10 text-neutral-500 hover:text-neutral-600 rounded-md transition ease-in delay-200" data-z-index="10" data-stacking-context="true" role="button" aria-labelledby="">
                                            <text color="rgb(115, 115, 115)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(115, 115, 115)" text-anchor="start" text-rendering="auto" unicode-bidi="normal" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(115, 115, 115)"/>
                                        </g>
                                        <g data-tag="button" id="bg-transparent4" class="bg-transparent font-sans px-1.5 py-1 z-10 text-neutral-500 hover:text-neutral-600 rounded-md transition ease-in delay-200" data-z-index="10" data-stacking-context="true" role="button" aria-labelledby="">
                                            <text color="rgb(115, 115, 115)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(115, 115, 115)" text-anchor="start" text-rendering="auto" unicode-bidi="normal" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(115, 115, 115)"/>
                                        </g>
                                    </g>
                                    <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="ui-sans-serif, system-ui, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                </g>
                            </g>
                        </g>
                        <g data-tag="div" id="flex3" class="flex flex-col flex-1 grow pb-12 w-11/12 md:w-full" data-z-index="auto" data-stacking-context="true" aria-owns="antialiased1">
                            <g data-tag="article" id="antialiased1" class="antialiased prose font-sans md:max-w-2/3 2xl:prose-lg dark:prose-invert justify-self-center mx-auto mb-16 w-full mt-10 break-words" data-z-index="auto" data-stacking-context="true" role="article" aria-owns="font-sans1 text-zinc-5001 flex4 leading-relaxed1 border-sprout-6001 flex5 border-sprout-6002 p-40pt1 border-sprout-6003 p-40pt2 h-[30vh]1">
                                <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                <g data-tag="h1" id="font-sans1" class="font-sans font-medium prose-h1" data-z-index="auto" data-stacking-context="true" role="heading" aria-level="1">
                                    <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="26.4px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="500" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                </g>
                                <g data-tag="div" id="text-zinc-5001" class="text-zinc-500 font-serif mb-2 font-light text-sm 2xl:text-lg" data-z-index="auto" data-stacking-context="true">
                                    <text color="rgb(113, 113, 122)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;Microsoft YaHei&quot;" font-size="15px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="300" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(113, 113, 122)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(113, 113, 122)"/>
                                </g>
                                <g data-tag="div" id="flex4" class="flex w-auto mb-10 justify-end items-end font-sans" data-z-index="auto" data-stacking-context="true" aria-owns="text-pretty1">
                                    <g data-tag="i" id="text-pretty1" class="text-pretty text-slate-500 text-start text-sm 2xl:text-lg font-mono leading-loose" data-z-index="auto" data-stacking-context="true"/>
                                </g>
                                <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                <g data-tag="p" id="leading-relaxed1" class="leading-relaxed font-sans text-base" data-z-index="auto" data-stacking-context="true">
                                    <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                </g>
                                <g data-tag="hr" id="border-sprout-6001" class="border-sprout-600" data-z-index="auto" data-stacking-context="true" role="separator" mask="url(#mask-for-border-sprout-60011)">
                                    <mask id="mask-for-border-sprout-60011">
                                        <rect width="688" height="0" x="172" y="-540.0078125" fill="#ffffff"/>
                                    </mask>
                                </g>
                                <g data-tag="div" id="flex5" class="flex justify-between w-full h-55 bg-[#FFFDF2]" data-z-index="auto" data-stacking-context="true" aria-owns="grow1 flex7">
                                    <g data-tag="div" id="grow1" class="grow flex flex-col justify-start justify-center" data-z-index="auto" data-stacking-context="true" aria-owns="m-auto1">
                                        <g data-tag="div" id="m-auto1" class="m-auto pr-20" data-z-index="auto" data-stacking-context="true" aria-owns="font-mono1 flex6">
                                            <g data-tag="div" id="font-mono1" class="font-mono text-[24pt]" data-z-index="auto" data-stacking-context="true">
                                                <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="&quot;Fira Code&quot;" font-size="32px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                            </g>
                                            <g data-tag="div" id="flex6" class="flex items-center" data-z-index="auto" data-stacking-context="true" aria-owns="text-[20pt]1 font-mono2">
                                                <g data-tag="div" id="text-[20pt]1" class="text-[20pt] pr-3 text-[#AAAAAA]" data-z-index="auto" data-stacking-context="true">
                                                    <text color="rgb(170, 170, 170)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="26.6667px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(170, 170, 170)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(170, 170, 170)"/>
                                                </g>
                                                <g data-tag="div" id="font-mono2" class="font-mono text-[24pt] text-[#FF4136]" data-z-index="auto" data-stacking-context="true">
                                                    <text color="rgb(255, 65, 54)" dominant-baseline="text-after-edge" font-family="&quot;Fira Code&quot;" font-size="32px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(255, 65, 54)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(255, 65, 54)"/>
                                                </g>
                                            </g>
                                        </g>
                                    </g>
                                    <g data-tag="div" id="flex7" class="flex justify-end" data-z-index="auto" data-stacking-context="true" aria-owns="w-full1">
                                        <g data-tag="img" id="w-full1" class="w-full h-full rounded-none" data-z-index="auto" data-stacking-context="true" role="img" mask="url(#mask-for-w-full11)">
                                            <mask id="mask-for-w-full11">
                                                <rect width="220" height="220" x="640" y="-508.0078125" fill="#ffffff"/>
                                            </mask>
                                        </g>
                                    </g>
                                </g>
                                <g data-tag="hr" id="border-sprout-6002" class="border-sprout-600" data-z-index="auto" data-stacking-context="true" role="separator" mask="url(#mask-for-border-sprout-60021)">
                                    <mask id="mask-for-border-sprout-60021">
                                        <rect width="688" height="0" x="172" y="-256.0078125" fill="#ffffff"/>
                                    </mask>
                                </g>
                                <g data-tag="div" id="p-40pt1" class="p-40pt flex justify-between w-full h-80 bg-[#FFFDF2]" data-z-index="auto" data-stacking-context="true" aria-owns="grow2 flex9">
                                    <g data-tag="div" id="grow2" class="grow flex flex-col justify-start justify-center" data-z-index="auto" data-stacking-context="true" aria-owns="grid1">
                                        <g data-tag="div" id="grid1" class="grid grid-rows-2" data-z-index="auto" data-stacking-context="true" aria-owns="mx-auto1 m-auto2">
                                            <g data-tag="div" id="mx-auto1" class="mx-auto pr-20 flex flex-col items-start justify-end" data-z-index="auto" data-stacking-context="true" aria-owns="text-[50pt]1">
                                                <g data-tag="div" id="text-[50pt]1" class="text-[50pt] leading-none text-zinc-600" data-z-index="auto" data-stacking-context="true">
                                                    <text color="rgb(82, 82, 91)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="66.6667px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(82, 82, 91)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(82, 82, 91)"/>
                                                </g>
                                            </g>
                                            <g data-tag="div" id="m-auto2" class="m-auto pl-5 pt-10" data-z-index="auto" data-stacking-context="true" aria-owns="font-mono3 flex8">
                                                <g data-tag="div" id="font-mono3" class="font-mono text-[12pt]" data-z-index="auto" data-stacking-context="true">
                                                    <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="&quot;Fira Code&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                                </g>
                                                <g data-tag="div" id="flex8" class="flex items-center" data-z-index="auto" data-stacking-context="true" aria-owns="text-[10pt]1 font-mono4">
                                                    <g data-tag="div" id="text-[10pt]1" class="text-[10pt] pr-1 text-[#AAAAAA]" data-z-index="auto" data-stacking-context="true">
                                                        <text color="rgb(170, 170, 170)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="13.3333px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(170, 170, 170)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(170, 170, 170)"/>
                                                    </g>
                                                    <g data-tag="div" id="font-mono4" class="font-mono text-[12pt] text-[#FF4136]" data-z-index="auto" data-stacking-context="true">
                                                        <text color="rgb(255, 65, 54)" dominant-baseline="text-after-edge" font-family="&quot;Fira Code&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(255, 65, 54)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(255, 65, 54)"/>
                                                    </g>
                                                </g>
                                            </g>
                                        </g>
                                    </g>
                                    <g data-tag="div" id="flex9" class="flex justify-end" data-z-index="auto" data-stacking-context="true" aria-owns="w-full2">
                                        <g data-tag="img" id="w-full2" class="w-full h-full rounded-none" data-z-index="auto" data-stacking-context="true" role="img" mask="url(#mask-for-w-full21)">
                                            <mask id="mask-for-w-full21">
                                                <rect width="213.34375" height="213.34375" x="593.328125" y="-170.6796875" fill="#ffffff"/>
                                            </mask>
                                        </g>
                                    </g>
                                </g>
                                <g data-tag="hr" id="border-sprout-6003" class="border-sprout-600" data-z-index="auto" data-stacking-context="true" role="separator" mask="url(#mask-for-border-sprout-60031)">
                                    <mask id="mask-for-border-sprout-60031">
                                        <rect width="688" height="0" x="172" y="127.9921875" fill="#ffffff"/>
                                    </mask>
                                </g>
                                <g data-tag="div" id="p-40pt2" class="p-40pt flex justify-between w-full h-80 bg-[#FFFDF2]" data-z-index="auto" data-stacking-context="true" aria-owns="grow3 flex11">
                                    <g data-stacking-layer="rootBackgroundAndBorders">
                                        <rect width="688" height="320" x="172" y="159.9921875" fill="rgb(255, 253, 242)"/>
                                    </g>
                                    <g data-tag="div" id="grow3" class="grow flex flex-col justify-start justify-center" data-z-index="auto" data-stacking-context="true" aria-owns="grid2">
                                        <g data-tag="div" id="grid2" class="grid grid-rows-2" data-z-index="auto" data-stacking-context="true" aria-owns="mx-auto2 m-auto3">
                                            <g data-tag="div" id="mx-auto2" class="mx-auto pr-20 flex flex-col items-start justify-end" data-z-index="auto" data-stacking-context="true" aria-owns="text-[27pt]1">
                                                <g data-tag="div" id="text-[27pt]1" class="text-[27pt] leading-none text-zinc-500" data-z-index="auto" data-stacking-context="true">
                                                    <text color="rgb(113, 113, 122)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="36px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(113, 113, 122)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(113, 113, 122)">
                                                        <tspan xml:space="preserve" x="229.3203125" y="323.9921875" lengthAdjust="spacingAndGlyphs">${title}</tspan>
                                                    </text>
                                                </g>
                                            </g>
                                            <g data-tag="div" id="m-auto3" class="m-auto pl-5 pt-10" data-z-index="auto" data-stacking-context="true" aria-owns="font-serif1 flex10">
                                                <g data-tag="div" id="font-serif1" class="font-serif text-[12pt]" data-z-index="auto" data-stacking-context="true">
                                                    <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;Microsoft YaHei&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)">
                                                    ${title ? `                                                                                                         <tspan xml:space="preserve" x="367.9375" y="381.4921875" textLength="102.78125" lengthAdjust="spacingAndGlyphs">blog.nyaw.xyz</tspan>
                                                        <tspan xml:space="preserve" x="367.9375" y="381.4921875" textLength="102.78125" lengthAdjust="spacingAndGlyphs">blog.nyaw.xyz</tspan>
                                                        ` : `
                                                          <tspan xml:space="preserve" x="307.9375" y="313.4921875" textLength="102.78125" lengthAdjust="spacingAndGlyphs">blog.nyaw.xyz</tspan>`}
                                                        
                                                    </text>
                                                </g>
                                                <g data-tag="div" id="flex10" class="flex items-end justify-self-end" data-z-index="auto" data-stacking-context="true" aria-owns="text-[10pt]2 font-sans2">
                                                    <g data-tag="div" id="text-[10pt]2" class="text-[10pt] pr-1 text-[#AAAAAA]" data-z-index="auto" data-stacking-context="true">
                                                        <text color="rgb(170, 170, 170)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="13.3333px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(170, 170, 170)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(170, 170, 170)">
                                                            <tspan xml:space="preserve" x="382.359375" y="405.9921875" textLength="14.8046875" lengthAdjust="spacingAndGlyphs">by</tspan>
                                                        </text>
                                                    </g>
                                                    <g data-tag="div" id="font-sans2" class="font-sans text-[12pt] text-[#FF4136] pl-3" data-z-index="auto" data-stacking-context="true">
                                                        <text color="rgb(255, 65, 54)" dominant-baseline="text-after-edge" font-family="&quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, Wotfard, &quot;TsangerYunHei W04&quot;" font-size="16px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(255, 65, 54)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(255, 65, 54)">
                                                            <tspan xml:space="preserve" x="413.1640625" y="405.4921875" textLength="57.5546875" lengthAdjust="spacingAndGlyphs">Secirian</tspan>
                                                        </text>
                                                    </g>
                                                </g>
                                            </g>
                                        </g>
                                    </g>
                                    <g data-tag="div" id="flex11" class="flex justify-end" data-z-index="auto" data-stacking-context="true" aria-owns="w-full3">
                                        <g data-tag="img" id="w-full3" class="w-full h-full rounded-none" data-z-index="auto" data-stacking-context="true" role="img" mask="url(#mask-for-w-full31)">
                                            <g data-stacking-layer="rootBackgroundAndBorders"/>
                                            <g data-stacking-layer="childStackingContextsWithNegativeStackLevels"/>
                                            <g data-stacking-layer="inFlowNonInlineNonPositionedDescendants"/>
                                            <g data-stacking-layer="nonPositionedFloats"/>
                                            <g data-stacking-layer="inFlowInlineLevelNonPositionedDescendants"/>
                                            <g data-stacking-layer="childStackingContextsWithStackLevelZeroAndPositionedDescendantsWithStackLevelZero"/>
                                            <g data-stacking-layer="childStackingContextsWithPositiveStackLevels"/>
                                            <mask id="mask-for-w-full31">
                                                <rect width="213.34375" height="213.34375" x="593.328125" y="213.3203125" fill="#ffffff"/>
                                            </mask>
                                            <g data-tag="img" role="img">
                                                <g class="svg-content typst-doc" data-view-box="0 0 85.03937007874016 85.03937007874016" data-width="213.34375" data-height="213.34375" transform="matrix(2.50876 0 0 2.50876 593.328 213.32)">
                                                    <path class="typst-shape" fill="rgb(255, 253, 242)" fill-rule="nonzero" d="M 0 0 L 0 85.03937 L 85.03937 85.03937 L 85.03937 0 Z " color="rgb(0, 0, 0)" stroke="none"/>
                                                    <g color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                        <g transform="matrix(1, 0, 0, 1, 0, 0)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                            <g class="typst-group" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                <g color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                    <g transform="matrix(1, 0, 0, 1, 0, 0)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(170, 170, 170)" stroke-width="0.2px" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 85.03937 C 0 85.03937 0 0 0 0 " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 14.1732, 0)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(170, 170, 170)" stroke-width="0.2px" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 85.03937 C 0 85.03937 0 0 0 0 " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 28.3465, 0)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(170, 170, 170)" stroke-width="0.2px" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 85.03937 C 0 85.03937 0 0 0 0 " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 42.5197, 0)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(170, 170, 170)" stroke-width="0.2px" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 85.03937 C 0 85.03937 0 0 0 0 " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 56.6929, 0)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(170, 170, 170)" stroke-width="0.2px" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 85.03937 C 0 85.03937 0 0 0 0 " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 70.8661, 0)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(170, 170, 170)" stroke-width="0.2px" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 85.03937 C 0 85.03937 0 0 0 0 " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 85.0394, 0)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(170, 170, 170)" stroke-width="0.2px" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 85.03937 C 0 85.03937 0 0 0 0 " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 0, 85.0394)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(170, 170, 170)" stroke-width="0.2px" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 0 C 0 0 85.03937 0 85.03937 0 " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 0, 70.8661)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(170, 170, 170)" stroke-width="0.2px" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 0 C 0 0 85.03937 0 85.03937 0 " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 0, 56.6929)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(170, 170, 170)" stroke-width="0.2px" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 0 C 0 0 85.03937 0 85.03937 0 " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 0, 42.5197)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(170, 170, 170)" stroke-width="0.2px" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 0 C 0 0 85.03937 0 85.03937 0 " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 0, 28.3465)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(170, 170, 170)" stroke-width="0.2px" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 0 C 0 0 85.03937 0 85.03937 0 " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 0, 14.1732)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(170, 170, 170)" stroke-width="0.2px" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 0 C 0 0 85.03937 0 85.03937 0 " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 0, 0)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(170, 170, 170)" stroke-width="0.2px" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 0 C 0 0 85.03937 0 85.03937 0 " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 14.1732, 14.1732)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="none" stroke="rgb(0, 0, 0)" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 28.346457 0 C 12.705336 0 0 12.705336 0 28.346457 C 0 28.346457 0 28.346457 0 28.346457 C 0 43.98758 12.705336 56.692913 28.346457 56.692913 C 28.346457 56.692913 28.346457 56.692913 28.346457 56.692913 C 43.98758 56.692913 56.692913 43.98758 56.692913 28.346457 C 56.692913 28.346457 56.692913 28.346457 56.692913 28.346457 C 56.692913 12.705336 43.98758 0 28.346457 0 C 28.346457 0 28.346457 0 28.346457 0 Z " color="rgb(0, 0, 0)"/>
                                                                    </g>
                                                                    <g transform="matrix(1, 0, 0, 1, 54.0544, 54.0544)" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" stroke="none">
                                                                        <path class="typst-shape" fill="rgb(255, 65, 54)" fill-rule="nonzero" d="M 8.503937 0 C 3.8116007 0 0 3.8116007 0 8.503937 C 0 8.503937 0 8.503937 0 8.503937 C 0 13.196274 3.8116007 17.007874 8.503937 17.007874 C 8.503937 17.007874 8.503937 17.007874 8.503937 17.007874 C 13.196274 17.007874 17.007874 13.196274 17.007874 8.503937 C 17.007874 8.503937 17.007874 8.503937 17.007874 8.503937 C 17.007874 3.8116007 13.196274 0 8.503937 0 C 8.503937 0 8.503937 0 8.503937 0 Z " color="rgb(0, 0, 0)" stroke="none"/>
                                                                    </g>
                                                                </g>
                                                            </g>
                                                        </g>
                                                    </g>
                                                </g>
                                            </g>
                                        </g>
                                    </g>
                                </g>
                                <g data-tag="div" id="h-[30vh]1" class="h-[30vh]" data-z-index="auto" data-stacking-context="true"/>
                            </g>
                        </g>
                        <g data-tag="div" id="relative2" class="relative bottom-0 w-full justify-between text-[10px] flex-nowrap flex" data-z-index="auto" data-stacking-context="true" aria-owns="flex12 flex14">
                            <g data-tag="div" id="flex12" class="flex items-center ml-1 px-0.5 my-1 hover:cursor-pointer group transition-all hover:bg-gray-200 rounded-sm" data-z-index="auto" data-stacking-context="true" aria-owns="flex13">
                                <g data-tag="div" id="flex13" class="flex items-center gap-1 group" data-z-index="auto" data-stacking-context="true" aria-owns="w-2.51 group-hover:opacity-1001">
                                    <g data-tag="div" id="w-2.51" class="w-2.5 h-2.5 rounded-full bg-sprout-300" data-z-index="auto" data-stacking-context="true"/>
                                    <g data-tag="div" id="group-hover:opacity-1001" class="group-hover:opacity-100 opacity-0 text-zinc-600" data-z-index="auto" data-stacking-context="true" opacity="0"/>
                                </g>
                            </g>
                            <g data-tag="div" id="flex14" class="flex justify-end items-center mr-3 space-x-1 flex-nowrap" data-z-index="auto" data-stacking-context="true">
                                <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="ui-sans-serif, system-ui, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;" font-size="10px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="ui-sans-serif, system-ui, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;" font-size="10px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="ui-sans-serif, system-ui, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;" font-size="10px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                                <text color="rgb(0, 0, 0)" dominant-baseline="text-after-edge" font-family="ui-sans-serif, system-ui, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;" font-size="10px" font-size-adjust="none" font-stretch="100%" font-style="normal" font-variant="normal" font-weight="400" direction="ltr" letter-spacing="normal" text-decoration="none solid rgb(0, 0, 0)" text-anchor="start" text-rendering="auto" unicode-bidi="isolate" word-spacing="0px" writing-mode="horizontal-tb" user-select="auto" fill="rgb(0, 0, 0)"/>
                            </g>
                        </g>
                    </g>
                    <g data-tag="button" id="!fixed1" class="!fixed bottom-5 right-5 p-3 mb-3 bg-sprout-200/60 hover:bg-sprout-300/75 rounded-md h-9 w-9 grid items-center justify-center duration-200 h-9 xl:h-12 w-9 xl:w-12 flex" data-z-index="auto" data-stacking-context="true" role="button" aria-labelledby="" aria-owns="i-ci-chevron-big-up1">
                        <g data-tag="div" id="i-ci-chevron-big-up1" class="i-ci-chevron-big-up" data-z-index="auto" data-stacking-context="true"/>
                    </g>
                </g>
            </g>
            <g data-tag="script" id="script3" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="script" id="script4" data-z-index="auto" data-stacking-context="true"/>
            <g data-tag="script" id="script5" data-z-index="auto" data-stacking-context="true"/>
        </g>
        <g data-tag="auto-scroll" id="auto-scroll1" data-z-index="auto" data-stacking-context="true"/>
        <g data-tag="grammarly-desktop-integration" id="grammarly-desktop-integration1" data-z-index="auto" data-stacking-context="true"/>
    </g>
</svg>`, {
      headers: { "content-type": "image/svg+xml" },
      status: 400
    }
    );
  } catch (e: any) {
    console.log(`${e.message}`);
    return new Response(`Failed to generate the image`, {
      status: 500,
    });
  }
}
