name: Hoist Branch

on:
  workflow_dispatch:
  push:
    branches: ["historia"]

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub auth token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}

      - uses: actions/checkout@main
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: 'historia'

      - name: New Born From Corp
        run: |
          git config --global user.email "gh@nyaw.xyz"
          git config --global user.name "Secirian"
          git checkout --orphan main
          git commit -m "+ every init"

      - name: Force Replace Former
        run: |
          git push origin main -f

      - name: Clean The Corp
        run: |
          curl -s -X DELETE -u ${{ steps.generate_token.outputs.token }} https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ github.head_ref }}
